name: Deploy to Production server

on:
  release:
    types: [published]

jobs:
  deploy:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NPM dependencies
        run: npm install

      - name: Compile assets
        run: npm run build

      - name: Deploy via rsync and sshpass
        env:
          USERNAME: ${{ secrets.SFTP_USERNAME }}
          PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          HOST: ${{ secrets.SFTP_HOST }}
          DEPLOY_PATH: postaverse.net/
        run: |
          sshpass -p "$PASSWORD" rsync -avz --exclude .env --exclude .git/ --exclude /node_modules/ --exclude /vendor/ --rsh="ssh -o StrictHostKeyChecking=no" . $USERNAME@$HOST:$DEPLOY_PATH
          sshpass -p "$PASSWORD" ssh $USERNAME@$HOST "cd $DEPLOY_PATH && which composer || (curl -sS https://getcomposer.org/installer | php && php composer.phar install --no-dev) && php --version && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan event:cache"
